#!/usr/bin/env sh

# BSPWM HOTKEYS

# Basic binds
super + Return
	$TERMINAL
super + d
	dmenu_run
#super + r
#	$TERMINAL -e $FILE
super + m
	$TERMINAL -e newsboat
super + c
	$TERMINAL -e cordless
#super + v
#	$TERMINAL -e nvim -c VimwikiIndex
super + shift + w
	$BROWSER

# MUSIC

# Pause audio
super + p
	mpc toggle
super + shift + p
	mpc pause; pauseallmpv
# Changes to next/previous tracks
super + {comma,period}
	mpc {prev,next}
# Restart track
super + shift + less
	mpc seek 0%
# Seek foward in song
super + {_,shift +} bracketright
	mpc seek +{10,120}
# Seek backward in song
super + {_,shift +} bracketleft
	mpc seek -{10,120}

# AUDIO

# Increase volume
super + {equal,plus}
	amixer sset Master {5,15}%+; pkill -RTMIN+10 blocks
# Decrease volume
super {_,shift +} + minus
	amixer sset Master {5,15}%-; pkill -RTMIN+10 blocks
super + shift + m
	amixer sset Master toggle; pkill -RTMIN+10 blocks

# WINDOW MANAGEMENT

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + {_,shift + }f
	bspc {desktop -l next,node -t ~fullscreen}

# rotate current node 90 degrees
super + y
	bspc node @focused:/ -R 90

# swap the current node and the biggest local node
super + space
	bspc node -s biggest.local || bspc node -s next.local

super + shift + Return
	bspc node -c

# STATE/FLAGS

# set the window state
super + {t,shift + t,s}
	bspc node -t {tiled,pseudo_tiled,floating}

# focus floating window
super + shift + space
	bspc node focused -t \~floating

# Make a window sticky/non-sticky
super + o
	bspc node -g sticky={on,off}

# FOCUS/SWAP

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

super + {g,semicolon}
	bspc desktop {prev,next}.occupied --focus
super + {Prior,Next}
	bspc desktop {prev,next}.occupied --focus
super + {Tab,backslash}
	bspc desktop last --focus

#super + {i,o}
#	bspc node -f {prev,next}.local

# focus or swap the next node
super + {_,shift + }c
	bspc node -{f,s} next.local

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'


# PRESELECT

#super + {u,o}
	#bspc node -p {south,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
#super + ctrl + shift + space
#	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel


# MOVE/RESIZE 

# expand a window by moving one of its side outward
super + shift + {y,u,i,o}
	bspc node -z {right -20 0,bottom 0 20,bottom 0 -20,right 20 0}

# contract a window by moving one of its side inward
#super + alt + shift + {h,j,k,l}
#	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# Toggle gaps
super + shift + d
	bspc config window_gap {0,15}
# Increase/descrease gap size
super { ,+ shift }+ z
	bspc config window_gap $(($(bspc config window_gap) {+,-} 3))

# --------------------------------- 

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}
